version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/src
    ports:
      - "${PORT:-8888}:${PORT:-8888}"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    networks:
      - app-network

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5435:5432"
    volumes:
      - pda:/var/lib/postgresql/data
    networks:
      - app-network
volumes:
  pda:

networks:
  app-network:
    driver: bridge